# Generated by Django 5.1.1 on 2024-10-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_converter', '0002_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='article_id',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
