# Generated by Django 5.1.1 on 2024-10-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_converter', '0003_images_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
