# Generated by Django 5.1.1 on 2024-10-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_converter', '0004_images_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_name',
            field=models.TextField(default=None),
        ),
    ]
